config/routes.rb
Rails.application.routes.draw do
  resources :scans
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/scan.rb
class Scan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  before_action :set_scan, only: [:show, :edit, :update, :destroy]

  # GET /scans
  # GET /scans.json
  def index
    @scans = Scan.all
  end

  # GET /scans/1
  # GET /scans/1.json
  def show
  end

  # GET /scans/new
  def new
    @scan = Scan.new
  end

  # GET /scans/1/edit
  def edit
  end

  # POST /scans
  # POST /scans.json
  def create
    @scan = Scan.new(scan_params)

    respond_to do |format|
      if @scan.save
        format.html { redirect_to @scan, notice: 'Scan was successfully created.' }
        format.json { render :show, status: :created, location: @scan }
      else
        format.html { render :new }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scans/1
  # PATCH/PUT /scans/1.json
  def update
    respond_to do |format|
      if @scan.update(scan_params)
        format.html { redirect_to @scan, notice: 'Scan was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan }
      else
        format.html { render :edit }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1
  # DELETE /scans/1.json
  def destroy
    @scan.destroy
    respond_to do |format|
      format.html { redirect_to scans_url, notice: 'Scan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan
      @scan = Scan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_params
      params.require(:scan).permit(:do_name, :do_description, :do_address, :do_phone, :do_fax)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scans_helper.rb
module ScansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScanDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td class="list_actions"><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/scans/_form.html.erb
<%= form_for(@scan) do |f| %>
  <% if @scan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scan.errors.count, "error") %> prohibited this scan from being saved:</h2>

      <ul>
      <% @scan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Название %><br>
    <%= f.text_field :do_name %>
  </div>
  <div class="field">
    <%= f.label :Описание %><br>
    <%= f.text_area :do_description %>
  </div>
  <div class="field">
    <%= f.label :Адрес %><br>
    <%= f.text_field :do_address %>
  </div>
  <div class="field">
    <%= f.label :Телефон %><br>
    <%= f.text_field :do_phone %>
  </div>
  <div class="field">
    <%= f.label :Факс %><br>
    <%= f.text_field :do_fax %>
  </div>
  <div class="actions">
    <%= f.submit value="Внести данные в БД" %>
  </div>
<% end %>

app/views/scans/edit.html.erb
<h1>Редактировать</h1>

<%= render 'form' %>

<%= link_to 'Показать', @scan %> |
<%= link_to 'Назад', scans_path %>

app/views/scans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Дочерние Общества</h1>

<table class="table">
  <thead>
    <tr>
      <th>Название Дочернего Общества</th>
      <th>Описание</th>
      <th>Адрес расположения</th>
      <th>Контактный телефон</th>
      <th>Факс</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scans.each do |scan| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= scan.do_name %></td>
        <td><%= scan.do_description %></td>
        <td><%= scan.do_address %></td>
        <td><%= scan.do_phone %></td>
        <td><%= scan.do_fax %></td>
        <td><%= link_to 'Показать информацию', scan %></td>
        <td><%= link_to 'Редактировать', edit_scan_path(scan) %></td>
        <td><%= link_to 'Удалить', scan, method: :delete, data: { confirm: 'Вы точно уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Внести Новое Дочернее Общесто', new_scan_path %>

app/views/scans/new.html.erb
<h1>Новое Дочернее Общество</h1>

<%= render 'form' %>

<%= link_to 'Назад', scans_path %>

app/views/scans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Дочернее Общество:</strong>
  <%= @scan.do_name %>
</p>

<p>
  <strong>Do description:</strong>
  <%= @scan.do_description %>
</p>

<p>
  <strong>Do address:</strong>
  <%= @scan.do_address %>
</p>

<p>
  <strong>Do phone:</strong>
  <%= @scan.do_phone %>
</p>

<p>
  <strong>Do fax:</strong>
  <%= @scan.do_fax %>
</p>

<%= link_to 'Редактировать', edit_scan_path(@scan) %> |
<%= link_to 'Назад', scans_path %>